spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=FundHive

spring.web.resources.static-locations[0]=file:src/main/resources/static/ 
spring.web.resources.static-locations[1]=classpath:/static/ 