spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=FundHive

spring.web.resources.static-locations[0]=file:src/main/resources/static/ 
spring.web.resources.static-locations[1]=classpath:/static/ 

auth0.domain=dev-c8ygr1a8yck0q556.us.auth0.com
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${auth0.domain}/

spring.ai.openai.api-key=${OPEN_AI_KEY}
#For debugging (optional):
logging.level.org.springframework.ai.chat.client.advisor=DEBUG