
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=FundHive

spring.web.resources.static-locations[0]=file:src/main/resources/static/ 
spring.web.resources.static-locations[1]=classpath:/static/ 

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_DOMAIN}

spring.ai.openai.api-key=${OPEN_AI_KEY}
#For debugging (optional):
logging.level.org.springframework.ai.chat.client.advisor=DEBUG